import { defineConfig } from "oxlint";
import core from "ultracite/oxlint/core";

export default defineConfig({
  extends: [core],
  ignorePatterns: core.ignorePatterns,
  rules: {
    "eslint/complexity": "off",
    "import/first": "off",
    "import/newline-after-import": "off",
    "eslint/no-control-regex": "off",
    "eslint/curly": "off",
    "eslint/func-style": "off",
    "eslint/max-classes-per-file": "off",
    "eslint/no-await-in-loop": "off",
    "eslint/no-bitwise": "off",
    "eslint/no-shadow": "off",
    "eslint/no-nested-ternary": "off",
    "eslint/no-promise-executor-return": "off",
    "eslint/no-use-before-define": "off",
    "eslint/prefer-destructuring": "off",
    "eslint/prefer-named-capture-group": "off",
    "eslint/preserve-caught-error": "off",
    "eslint/require-await": "off",
    "eslint/require-unicode-regexp": "off",
    "eslint/sort-keys": "off",
    "jsdoc/check-tag-names": "off",
    "promise/prefer-await-to-then": "off",
    "promise/avoid-new": "off",
    "promise/prefer-await-to-callbacks": "off",
    "typescript/no-non-null-assertion": "off",
    "typescript/method-signature-style": "off",
    "unicorn/consistent-function-scoping": "off",
    "unicorn/filename-case": "off",
    "unicorn/import-style": "off",
    "unicorn/no-array-sort": "off",
    "unicorn/no-await-expression-member": "off",
    "unicorn/prefer-event-target": "off",
    "unicorn/prefer-structured-clone": "off",
    "unicorn/require-post-message-target-origin": "off",
  },
});
