import { defineConfig } from "oxlint";
import core from "ultracite/oxlint/core";

const deferredRules = Object.fromEntries(
  [
    "eslint/max-classes-per-file",
    "import/newline-after-import",
    "import/no-duplicates",
    "import/no-named-as-default-member",
    "node/callback-return",
    "promise/prefer-catch",
    "typescript/method-signature-style",
    "typescript/no-confusing-non-null-assertion",
    "typescript/no-dynamic-delete",
    "typescript/no-import-type-side-effects",
    "typescript/parameter-properties",
    "unicorn/catch-error-name",
    "unicorn/consistent-assert",
    "unicorn/consistent-existence-index-check",
    "unicorn/custom-error-definition",
    "unicorn/error-message",
    "unicorn/escape-case",
    "unicorn/no-array-for-each",
    "unicorn/no-array-reverse",
    "unicorn/no-hex-escape",
    "unicorn/no-immediate-mutation",
    "unicorn/no-lonely-if",
    "unicorn/no-negated-condition",
    "unicorn/no-new-array",
    "unicorn/no-object-as-default-parameter",
    "unicorn/no-thenable",
    "unicorn/no-unreadable-array-destructuring",
    "unicorn/no-useless-fallback-in-spread",
    "unicorn/no-useless-promise-resolve-reject",
    "unicorn/no-useless-spread",
    "unicorn/prefer-add-event-listener",
    "unicorn/prefer-array-index-of",
    "unicorn/prefer-bigint-literals",
    "unicorn/prefer-code-point",
    "unicorn/prefer-dom-node-append",
    "unicorn/prefer-export-from",
    "unicorn/prefer-import-meta-properties",
    "unicorn/prefer-includes",
    "unicorn/prefer-logical-operator-over-ternary",
    "unicorn/prefer-query-selector",
    "unicorn/prefer-regexp-test",
    "unicorn/prefer-response-static-json",
    "unicorn/prefer-spread",
    "unicorn/prefer-string-replace-all",
    "unicorn/prefer-ternary",
    "unicorn/prefer-type-error",
    "unicorn/switch-case-braces",
  ].map((rule) => [rule, "off"]),
);

export default defineConfig({
  extends: [core],
  ignorePatterns: core.ignorePatterns,
  rules: {
    ...deferredRules,
    "import/consistent-type-specifier-style": "off",
    "promise/param-names": "off",
    "typescript/array-type": "off",
    "typescript/consistent-type-definitions": "off",
    "typescript/consistent-type-imports": "off",
    "eslint/curly": "off",
    "eslint/no-await-in-loop": "off",
    "eslint/no-bitwise": "off",
    "eslint/no-shadow": "off",
    "eslint/no-nested-ternary": "off",
    "eslint/no-use-before-define": "off",
    "eslint/func-style": "off",
    "eslint/complexity": "off",
    "eslint/prefer-named-capture-group": "off",
    "eslint/require-await": "off",
    "eslint/require-unicode-regexp": "off",
    "eslint/sort-keys": "off",
    "jsdoc/check-tag-names": "off",
    "promise/prefer-await-to-then": "off",
    "promise/avoid-new": "off",
    "promise/prefer-await-to-callbacks": "off",
    "typescript/no-non-null-assertion": "off",
    "unicorn/consistent-function-scoping": "off",
    "unicorn/filename-case": "off",
    "unicorn/import-style": "off",
    "unicorn/no-array-sort": "off",
    "unicorn/no-await-expression-member": "off",
    "unicorn/no-useless-undefined": "off",
    "unicorn/numeric-separators-style": "off",
    "unicorn/prefer-event-target": "off",
    "unicorn/require-post-message-target-origin": "off",
    "unicorn/text-encoding-identifier-case": "off",
  },
});
