allowBuilds:
  "@mongodb-js/zstd": false
  esbuild: true
  node-liblzma: false
  sharp: false
  unrs-resolver: false

overrides:
  ohash: 2.0.11

minimumReleaseAgeExclude:
  - "@ai-sdk/*"
  - "@rolldown/*"
  - "@vercel/*"
  - "@workflow/*"
  - ai
  - experimental-ai-sdk-code-mode
  - eve
  - nitro
  - rolldown
  - workflow
  - "@better-auth/core@1.6.29"
  - "@better-auth/drizzle-adapter@1.6.29"
  - "@better-auth/kysely-adapter@1.6.29"
  - "@better-auth/memory-adapter@1.6.29"
  - "@better-auth/mongo-adapter@1.6.29"
  - "@better-auth/prisma-adapter@1.6.29"
  - "@better-auth/telemetry@1.6.29"
  - better-auth@1.6.29
  - "@better-auth/infra@0.4.5"

patchedDependencies:
  '@emulators/core@0.10.0': patches/@emulators__core@0.10.0.patch
