import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { build } from "vite";
import { format } from "prettier";

async function main() {
  const temporaryDirectory = await mkdtemp(join(tmpdir(), "autograph-mcp-ui-"));
  try {
    await build({
      configFile: false,
      logLevel: "warn",
      build: {
        cssCodeSplit: false,
        emptyOutDir: true,
        minify: true,
        outDir: temporaryDirectory,
        rollupOptions: {
          input: resolve("lib/mcp/session-app/index.tsx"),
          output: {
            entryFileNames: "app.js",
            assetFileNames: "[name][extname]",
            format: "iife",
            inlineDynamicImports: true,
          },
        },
      },
    });
    const [javascript, css] = await Promise.all([
      readFile(join(temporaryDirectory, "app.js"), "utf8"),
      readFile(join(temporaryDirectory, "style.css"), "utf8"),
    ]);
    const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Autograph App Builder</title><style>${css}</style></head><body><div id="root"></div><script>${javascript}</script></body></html>`;
    const source = await format(
      `// Generated by scripts/build-mcp-session-ui.ts.\nexport const generatedSessionUiHtml = ${JSON.stringify(html)};\n`,
      { parser: "typescript" },
    );
    await writeFile(resolve("lib/mcp/session-ui.generated.ts"), source);
  } finally {
    await rm(temporaryDirectory, { recursive: true, force: true });
  }
}

void main();
