import { posix } from "node:path";

import type { SandboxSeedFile } from "eve/sandbox";

import { HOSTED_MANAGED_SKILL_CONTENTS } from "./hosted-managed-seeds.generated";

export const HOSTED_MANAGED_SKILLS_SOURCE = "agent/skills";
export const HOSTED_MANAGED_SKILLS_TARGET = "$HOME/.agents/skills";

/**
 * Reconstructs Eve's current managed skill seed set for runtime template
 * recovery from generated bytes embedded in Eve's separate service bundle.
 */
export function readHostedManagedSeedFiles(): readonly SandboxSeedFile[] {
  return HOSTED_MANAGED_SKILL_CONTENTS.map(({ content, path }) => ({
    content: Buffer.from(content, "utf8"),
    path: posix.join(HOSTED_MANAGED_SKILLS_TARGET, path),
  }));
}
