import { lstatSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const repositoryRoot = path.resolve(process.cwd());
const skillSourceRoot = path.join(repositoryRoot, "agent/skills");
const skillOutputPath = path.join(repositoryRoot, "lib/sandbox/hosted-managed-seeds.generated.ts");

const listRegularFiles = (directory: string, relativeDirectory = "."): string[] => {
  const files: string[] = [];
  for (const entry of readdirSync(directory, { withFileTypes: true })) {
    const relativePath = path.posix.join(relativeDirectory, entry.name);
    const absolutePath = path.join(directory, entry.name);
    if (entry.isDirectory()) {
      files.push(...listRegularFiles(absolutePath, relativePath));
      continue;
    }
    if (!entry.isFile() || !lstatSync(absolutePath).isFile())
      throw new Error(
        `The hosted managed seed source contains an unsupported entry: ${relativePath}`,
      );
    files.push(relativePath);
  }
  return files;
};

const skillEntries = listRegularFiles(skillSourceRoot)
  .toSorted((left, right) => left.localeCompare(right))
  .map((relativePath) => ({
    content: readFileSync(path.join(skillSourceRoot, relativePath), "utf-8"),
    path: relativePath,
  }));

if (skillEntries.length === 0) throw new Error("The hosted managed skill seed set is empty.");

const generatedSkills = `// Generated by mise run hosted:generate-runtime-assets. Do not edit.
export const HOSTED_MANAGED_SKILL_CONTENTS = ${JSON.stringify(skillEntries, null, 2)} as const;
`;
writeFileSync(skillOutputPath, generatedSkills);
