import { createHash } from "node:crypto";
import { lstatSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, posix, resolve } from "node:path";

import { format } from "prettier";

const repositoryRoot = resolve(process.cwd());
const skillSourceRoot = join(repositoryRoot, "agent/skills");
const skillOutputPath = join(
  repositoryRoot,
  "lib/sandbox/hosted-managed-seeds.generated.ts",
);
const artifactSourcePath = join(
  repositoryRoot,
  "artifacts/hosted/arrusted-ffa0c34a-preview.tar.gz",
);
const artifactOutputPath = join(
  repositoryRoot,
  "lib/sandbox/hosted-artifact.generated.ts",
);

function listRegularFiles(
  directory: string,
  relativeDirectory = ".",
): string[] {
  const files: string[] = [];
  for (const entry of readdirSync(directory, { withFileTypes: true })) {
    const relativePath = posix.join(relativeDirectory, entry.name);
    const absolutePath = join(directory, entry.name);
    if (entry.isDirectory()) {
      files.push(...listRegularFiles(absolutePath, relativePath));
      continue;
    }
    if (!entry.isFile() || !lstatSync(absolutePath).isFile())
      throw new Error(
        `The hosted managed seed source contains an unsupported entry: ${relativePath}`,
      );
    files.push(relativePath);
  }
  return files;
}

const skillEntries = listRegularFiles(skillSourceRoot)
  .sort((left, right) => left.localeCompare(right))
  .map((path) => ({
    path,
    content: readFileSync(join(skillSourceRoot, path), "utf8"),
  }));

if (skillEntries.length === 0)
  throw new Error("The hosted managed skill seed set is empty.");

const generatedSkills = await format(
  `// Generated by mise run hosted:generate-runtime-assets. Do not edit.
export const HOSTED_MANAGED_SKILL_CONTENTS = ${JSON.stringify(skillEntries, null, 2)} as const;
`,
  { filepath: skillOutputPath },
);
writeFileSync(skillOutputPath, generatedSkills);

const artifactBytes = readFileSync(artifactSourcePath);
const artifactSha256 = createHash("sha256").update(artifactBytes).digest("hex");
const generatedArtifact = `// Generated by mise run hosted:generate-runtime-assets. Do not edit.
export const HOSTED_ARTIFACT_BASE64 = ${JSON.stringify(artifactBytes.toString("base64"))};
export const HOSTED_ARTIFACT_EMBEDDED_BYTES = ${String(artifactBytes.byteLength)};
export const HOSTED_ARTIFACT_EMBEDDED_SHA256 = ${JSON.stringify(artifactSha256)};
`;
writeFileSync(artifactOutputPath, generatedArtifact);
